### PR TITLE
jib-support: building docker image for user spring boot app via jib and

### PR DESCRIPTION
**Pull request by Wawrzyniec-Nowak**
pushing it to remote repository

### CODE REVIEW

**Comment by Wawrzyniec-Nowak** [comment]
For the sake of testing it on kubernetes cluster execute commands:
```
kubectl run into --image=intomicroservices/user-spring-boot-app:latest --port=8080
kubectl expose pod into --type=LoadBalancer
```
then you can access endpoints calling _localhost:8080/actuator_ i.e.

**Review by psieniawski — COMMENTED** [review]
What will happen in case of local build? Will the plugin try to place the image into the repository?

**Comment by Wawrzyniec-Nowak** [comment]
> What will happen in case of local build? Will the plugin try to place the image in the repository?

You mean while running mvn clean install command locally? It will not push the image to repository. As I understand you need to explicitly run jib:build to build/push the image

**Comment by psieniawski** [comment]
> > What will happen in case of local build? Will the plugin try to place the image in the repository?
> 
> You mean while running mvn clean install command locally? It will not push the image to repository. As I understand you need to explicitly run jib:build to build/push the image

If so, then fine with me, but we must also think about images for different setups like inmem and redis user repos we have now. Probably separate images with separate ... names or tags?

**Review by psieniawski — APPROVED** [review]
Fine with me as long as jib plugin does not try to push the image automagically without explicit request.

**Comment by Wawrzyniec-Nowak** [comment]
> > > What will happen in case of local build? Will the plugin try to place the image in the repository?
> > 
> > 
> > You mean while running mvn clean install command locally? It will not push the image to repository. As I understand you need to explicitly run jib:build to build/push the image
> 
> If so, then fine with me, but we must also think about images for different setups like inmem and redis user repos we have now. Probably separate images with separate ... names or tags? I'm not sure, don't have that much experience with docker. I just want to point the issue I see now.

Totally agree

**Pull request merged**
